fields
htmlacademy-php/1228111-doingsdone-12 pull request #11
Opened 2021-05-03 21:03 UTC by marinahaid

2021-05-11 15:22 UTC, ademaro commented on add.php
> +        $all_tasks = select_tasks($con, $user_id);
зачем нам список задач и категорий при отправке формы?

2021-05-12 11:55 UTC, ademaro commented on templates/main.php
> +<div class="content"><?= $left_content; ?></div>
У нас левая колонка на всех страницах, логичнее вытащить эту строку в layout, а не в каждый шаблон страницы, не?)

2021-05-13 12:29 UTC, marinahaid commented on add.php
> +        $all_tasks = select_tasks($con, $user_id);
не зачем, просто иначе при при отправке формы пробадают в левом меню проекты и задачи

2021-05-13 12:29 UTC, marinahaid commented on templates/main.php
> +<div class="content"><?= $left_content; ?></div>
такого у меня в текущей ветке нет, поробую еще раз сохранить и закоммитить

2021-05-21 13:43 UTC, ademaro commented on add-task.php
> +    if (is_date_valid($_POST['date']) === false) {
достаточно будет `if (!is_date_valid($_POST['date'])) {`

2021-05-21 13:49 UTC, ademaro requested changes
Слушай, ну очень круто, ты молодец! Давай небольшие поправки сделаем и двинем дальше

2021-05-21 13:49 UTC, ademaro commented on templates/form-task.php
> +            <input class="form__input <?= $errors['name'] ? 'form__input--error' : ''; ?>" type="text" name="name" id="name" value="<?= !empty($_POST['name']) ? $_POST['name'] : $_POST['name']; ?>" p
https://github.com/ademaro/backend-tips — почитай про тернарный оператор, можем писать более лаконично

2021-05-21 13:49 UTC, ademaro commented on templates/form-task.php
> +            <input class="form__input <?= $errors['name'] ? 'form__input--error' : ''; ?>" type="text" name="name" id="name" value="<?= !empty($_POST['name']) ? $_POST['name'] : $_POST['name']; ?>" p
`!empty($_POST['name']) ? $_POST['name'] : $_POST['name']` — ну и тут у тебя, видимо, опечатка...

2021-05-21 13:49 UTC, ademaro commented on templates/form-task.php
> +            if ($errors['name']) : ?>
`if (!empty($errors['name']))` — всё-таки лучше такую проверку сделать

2021-05-21 13:49 UTC, ademaro commented on templates/form-task.php
> +                <p class="form__message">Заполните корректно поле</p>
У тебя текст ошибок как раз хранится в массиве $errors, давай оттуда и выводить его

2021-05-21 13:49 UTC, ademaro commented on workspace.code-workspace
> +}
Этот файл не нужен в проекте, давай удалим

2021-06-01 17:21 UTC, merged